version: '3.8'

services:
  redis:
    image: redis:7.4-alpine
    container_name: french-admin-redis
    ports:
      - "6379:6379"
    restart: always
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis_data:/data

  qdrant:
    image: qdrant/qdrant:v1.12.0
    container_name: french-admin-qdrant
    ports:
      - "6333:6333"
    environment:
      - QDRANT__SERVICE__API_KEY=${QDRANT_API_KEY}
    restart: always
    volumes:
      - qdrant_data:/qdrant/storage

  app:
    build: .
    container_name: french-admin-app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - QDRANT_HOST=qdrant
      - REDIS_HOST=redis
      - QDRANT_API_KEY=${QDRANT_API_KEY}
    depends_on:
      - redis
      - qdrant
    command: >
      bash -c "uv run uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  redis_data:
  qdrant_data:
