apiVersion: v1
kind: ConfigMap
metadata:
  name: rag-config
  namespace: french-admin-rag
data:
  # Application Environment Variables
  ENVIRONMENT: "production"
  DEBUG: "False"
  LLM_PROVIDER: "openai"
  LLM_MODEL: "gpt-4o-mini"
  QDRANT_HOST: "qdrant-svc"
  QDRANT_PORT: "6333"
  REDIS_HOST: "redis-svc"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  OLLAMA_BASE_URL: "http://ollama-svc:11434" # If using local model
